### ISSUE TITLE
Error message when opening the Excel output

### ISSUE THREAD

**Issue by ericknizard** [TheInformationLab/Tableau-Extension-ExportAll#23]
Hi,

downloaded the extension and tested it in a dashboard.

It generates the excel file but when opening it, I get the message below

![image](https://user-images.githubusercontent.com/32941736/69380793-3ce24e00-0c81-11ea-98fc-dff78f7171a9.png)

Then, once opened in Repaired mode, I get the following 

![image](https://user-images.githubusercontent.com/32941736/69380848-6307ee00-0c81-11ea-9831-f0d68efe2288.png)

Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Repaired Records: Cell information from /xl/worksheets/sheet1.xml part

but no more details ... anyone experiencing the same issue?

**Comment by aeshepherd1** [comment]
I get exactly the same message as ericknizard.  This happens when the number of rows I am attempting to export gets above around 2,500, according to some testing I did on my own dashboard.  I know a previous thread within the Tableau community mentioned a limit of about 1,500 that someone else was getting.   My understanding from that thread was that this limitation was corrected in v2.  I downloaded the extension from the Tableau Extension Gallery.  I noticed when I looked at the Gallery today that the Export All extension says it is version 1.0.0, which confuses me since I read somewhere that v2 had been released.  Here is the initial thread:  https://community.tableau.com/thread/284383

**Comment by aeshepherd1** [comment]
I am updating my previous comment about downloading to Excel.  In doing some further testing, it appears that the issue I had was not the number of records exported, but rather related to Issue #7.  I was getting the error because of null values in some numeric fields.  I see that that has been marked as a bug already.

**Comment by craigbloodworth** [comment]
This should now be fixed in the latest release [2.2.0](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/releases/tag/v2.2.0)
