### ISSUE TITLE
Making this a sandboxed extension

### ISSUE THREAD

**Issue by leefinar** [TheInformationLab/Tableau-Extension-ExportAll#29]
Do you think you will make this a sandbox extension?  I would love for this to run on our servers rather than network enabled.

**Comment by AldenStowe** [comment]
I think that the only issues here for submission as a sandbox extension are the dependencies which, in order to be sandboxed, should exist inside the project (using relative links) and not be referenced on the web,

See the requirements here: https://tableau.github.io/extensions-api/docs/trex_sandbox_test.html

**Comment by craigbloodworth** [comment]
@leefinar I would love this to be a sandboxed extension however @AldenStowe the blocker isn't dependency mapping. Tableau have effectively prevented this extension from ever being sandboxed as the security limitations of a sandboxed extension block the download function which the extension depends upon.

As an original advocate for sandboxing extensions I share everyone's frustration
