### ISSUE TITLE
Does the extension work with Viewer licenses?

### ISSUE THREAD

**Issue by jessicalois** [TheInformationLab/Tableau-Extension-ExportAll#34]
Tableau currently cannot provide us with a viewer license to test if our use of the extension will work if we switch from Explorer to Viewer for our users. Is this something the developer can answer? Or has anyone else successfully used the extension with Viewer licenses?

**Comment by andre347** [comment]
This extension works regardless of which license type the dashboard user has. One thing to note is that viewers can only interact with the dashboard and cannot create content or configure the dashboard (and the extension) because they don't have a Tableau Desktop compatible license (nor can they configure the dashboard and extension in web edit mode). So this should work fine.
