### ISSUE TITLE
Extension not working on Server

### ISSUE THREAD

**Issue by melanatech** [TheInformationLab/Tableau-Extension-ExportAll#62]
I've been following the updates diligently since the new update on Wednesday, and while I see issues being resolved my issue persists. I don't mind sending a copy of the packaged workbook, but essentially the extension is blocked on Server while it works without issue on Desktop. I have included a video demonstration here (for the author only, password in the uploaded .twbx file) https://www.loom.com/share/79fe127c424c461aaf249347a5177a12

I'm using Tableau Desktop 2020.2.5, Tableau Server 2020.2.0, and Google Chrome Version 85.0.4183.83 (Official Build) (64-bit). I tested the issue on Safari as well, so I don't think it's just a browser issue.

<img width="710" alt="Screen Shot 2020-08-28 at 12 09 21 PM" src="https://user-images.githubusercontent.com/20934522/91589237-64102f00-e927-11ea-987f-f69be8d575b4.png">
<img width="710" alt="Screen Shot 2020-08-28 at 12 09 12 PM" src="https://user-images.githubusercontent.com/20934522/91589246-67a3b600-e927-11ea-9705-7e94bf529316.png">
<img width="710" alt="Screen Shot 2020-08-28 at 12 08 51 PM" src="https://user-images.githubusercontent.com/20934522/91589249-696d7980-e927-11ea-895c-6771144393ba.png">
<img width="710" alt="Screen Shot 2020-08-28 at 12 08 40 PM" src="https://user-images.githubusercontent.com/20934522/91589253-6b373d00-e927-11ea-8b94-fccaa0556de1.png">
<img width="710" alt="Screen Shot 2020-08-28 at 12 08 09 PM" src="https://user-images.githubusercontent.com/20934522/91589254-6bcfd380-e927-11ea-86f6-500d274f8225.png">

**Comment by craigbloodworth** [comment]
Hi @melanatech. Thank you for raising this issue. It's an interesting one as it's an error raised in the @tableau extension api, rather than the Export All code. Please feel free to drop your workbook [here](https://fileshare.theinformationlab.co.uk/index.php/s/puLCy00gDHKr67D) and I can raise it with the extensibility team at Tableau if needed.

**Comment by melanatech** [comment]
Thanks, I added it earlier but I'll reupload in case it got lost: melanatech issue #62.twbx

**Comment by craigbloodworth** [comment]
I've tested this on Server 2020.2.4 and it works just fine. The version you're using 2020.2.0 is no longer available for download and Tableau recommends an immediate upgrade. I'm going to test with Server 2020.2.1 just as soon as it installs

**Comment by craigbloodworth** [comment]
I've managed to replicate the issue and have fixed it @melanatech

Can you please confirm so I can close the issue? I've also noticed you're using the beta URL. You might want to switch to the main prod version (remove -beta) from the url in the .trex file.

**Comment by melanatech** [comment]
Ok, I'm testing now.

**Comment by melanatech** [comment]
@craigbloodworth it's working now! But I'm a little confused. The trex version that is working is the old one I had (which references version 1.0.0), and when I removed the "-beta" from the new trex version url (which I realize I got from the public folder here on github) I get this:

<img width="254" alt="Screen Shot 2020-09-01 at 1 58 23 PM" src="https://user-images.githubusercontent.com/20934522/91889065-3561c380-ec5b-11ea-8ccf-04daf6d1646b.png">

Not sure if it matters which one I use since the export is working now, but just thought you should know.

**Comment by craigbloodworth** [comment]
@melanatech the error you're seeing there is from Tableau Server and is because the new URL hasn't been added to your site's extension white list. To do this go to the site's settings page, click on the Extensions tab and add the url "https://exportallextension.theinformationlab.io" to the white list. You can set 'Full Data Access' to deny as the extension doesn't require full data access and you can auto hide the user prompts if you wish.

As all seems well I'm going to close this issue. Thanks for helping with debugging and for being understanding as I try and sort the issue.
